#!/bin/sh
set -e

# useful variables
share_dir="QW share_dir WQ"
sm_dir="QW sm_dir WQ"

# create service user
if ! getent passwd splintermail >/dev/null ; then
    useradd --system --no-create-home --shell /bin/false splintermail
fi

# create the splintermail directory
if [ ! -d "$sm_dir" ] ; then
    mkdir -p "$sm_dir"
    chmod 700 "$sm_dir"
    chown splintermail:splintermail "$sm_dir"
fi

# service should get started in stubs written by debhelper
#DEBHELPER#
