#!/bin/sh
set -e

# useful variables
share_dir="QWER share_dir REWQ"
sm_dir="QWER sm_dir REWQ"
old_ca_file="$sm_dir/QWER old_ca_name REWQ"
old_key_file="$sm_dir/QWER old_key_name REWQ"
old_cert_file="$sm_dir/QWER old_cert_name REWQ"
ca_file="$sm_dir/QWER ca_name REWQ"
key_file="$sm_dir/QWER key_name REWQ"
cert_file="$sm_dir/QWER cert_name REWQ"

# create service user
if ! getent passwd splintermail >/dev/null ; then
    useradd --system --no-create-home --shell /bin/false splintermail
fi

# create the splintermail directory
if [ ! -d "$sm_dir" ] ; then
    mkdir -p "$sm_dir"
    chmod 700 "$sm_dir"
    chown -R splintermail:splintermail "$sm_dir"
fi

# migrate old certificates from v0.2 installations
if [ -f "$old_cert_file" ] ; then
    mv "$old_cert_file" "$cert_file"
fi
if [ -f "$old_key_file" ] ; then
    mv "$old_key_file" "$key_file"
fi
if [ -f "$old_ca_file" ] ; then
    mv "$old_ca_file" "$ca_file"
fi

# generate the SSL certificates, if they don't exist already
if [ ! -f "$cert_file" ] || [ ! -f "$key_file" ] || [ ! -f "$ca_file" ] ; then
    # generate the files
    sh "$share_dir/keygen.sh" "$share_dir/openssl.cnf" "$sm_dir"
    # trust the generated certificate authority
    cp "$ca_file" "/usr/local/share/ca-certificates"
    update-ca-certificates
    # make sure splintermail can read them
    chown splintermail:splintermail "$ca_file" "$key_file" "$cert_file"
fi

# service should get started in stubs written by debhelper
#DEBHELPER#
