#!/bin/sh
set -e

action="$1"

if [ "$action" = "purge" ] ; then
    # delete files
    rm -rf "QW sm_dir WQ"
    # not deleting service user, I agree with Fedora's guidlines
    # https://fedoraproject.org/wiki/Packaging:UsersAndGroups
    # # delete service user
    # userdel --force splintermail > /dev/null || true
fi

# service should get removed in stubs written by debhelper
#DEBHELPER#
