#!/bin/sh

set -e

# check if there is a version of splintermail already installed
if pkgutil --pkgs | grep -q QW osx_pkg_id WQ ; then
    upgrading="true"
else
    upgrading="false"
fi

# if there was a version installed, call the preupgrade script
if [ "$upgrading" = "true" ] ; then
    sh "QW share_dir WQ/preupgrade.sh" || true
fi

exit 0
