#!/bin/sh

# check if there is a version of splintermail already installed
if pkgutil --pkgs | grep -q QWER osx_pkg_id REWQ ; then
    upgrading="true"
else
    upgrading="false"
fi

# if there was a version installed, call the preupgrade script
if [ "$upgrading" = "true" ] ; then
    sh "QWER share_dir REWQ/preuninstall.sh"
fi

exit 0
