#!/bin/sh

# check if there is a version of splintermail installed
if pkgutil --pkgs | grep -q QW osx_pkg_id WQ ; then
    uninstalling="true"
else
    uninstalling="false"
fi

# if there was a version installed, call the preuninstall script
if [ "$uninstalling" = "true" ] ; then
    sh "QW share_dir WQ/preuninstall.sh"
fi

exit 0
