.TH splintermail 1  "July 2018" "version QW version WQ" "User Commands"
\"
.SH NAME
\"
.B splintermail
\- QW pkgdescr_short WQ
\"
.SH SYNOPSIS
\"
QW "\n.PP\n"^[for c=subcommands -> ".B splintermail\n%s [OPTIONS]"%c] WQ
.SH DESCRIPTION
QW man_escape(pkgdescr_long(width="10000" joiner="\n\n")) WQ
\"
.SH OPTIONS
\"
QW man_escape("\n"^[for o=opts_common -> optcall(manopt o)]) WQ
.SS CITM-specific options:
\d
QW man_escape("\n"^[for o=opts_citm -> optcall(manopt o)]) WQ
.SS CONFIGURE-specific options:
\d
QW man_escape("\n"^[for o=opts_configure -> optcall(manopt o)]) WQ
.SS STATUS-specific options:
\d
QW man_escape("\n"^[for o=opts_status -> optcall(manopt o)]) WQ
.SS ACCOUNT_COMMANDS-specific options:
\d
QW man_escape("\n"^[for o=opts_apis -> optcall(manopt o)]) WQ
\"
.SH ACCCOUNT COMMANDS
\fBsplintermail\fR can be used to control nearly all the aspects of your
account from the command line.
\"
.SS General Commands
\"
QW man_escape("\n"^[for a=apis_general -> apicall(manapi a)]) WQ
\"
.SS Alias Commands
Splintermail supports two different types of aliases: Random Aliases and
Primary Aliases.  Both sending and receiving are support for all aliases.
\"
Random Aliases are used to protect your online identity.  Whenever a new
website asks for your email address, give them a new random alias!  If you then
start to recieve spam on that address, you know exactly which website is
guilty, and you can safely delete that alias without affecting your other
web accounts.  Deleted random aliases are not reused and no log of the original
owner is kept, so if you delete an address neither you nor any other
Splintermail user will be able to use that alias in the future.  This ensures
that nobody else can gain access to any web accounts you opened with that alias.
\"
Primary aliases are a convenience feature for users who wish to control
multiple non-random email addresses with the ease of only checking one account.
For example, a single user might want to recieve mail at
"jdoe@splintermail.com" and "captain_danger@splintermail.com".  Primary
aliases, like your account username, are offered on a first-come-first-serve
basis, and can be reused after they are deleted (even by somebody else).
\"
QW man_escape("\n"^[for a=apis_aliases -> apicall(manapi a)]) WQ
\"
.SS Device Commands
Each device represents a computer where you are able to receive encrypted email.
Deleting a device will cause new messages to be encrypted in a way that the
corresponding computer will no longer be able to read them.  Note that if you
have not changed your password and the deleted device is still trying to check
email on your behalf, the deleted device may re-register itself.
\"
QW man_escape("\n"^[for a=apis_devices -> apicall(manapi a)]) WQ
\"
.SS Token Commands
Each API token represents a computer where you have authorized the automatic
usage of the splintermail command-line tool.  You can remove authorization by
deleting the corresponding token.
\"
QW man_escape("\n"^[for a=apis_tokens -> apicall(manapi a)]) WQ
\"
.SS Installation Commands
QW apis.list_installations.long WQ

QW apis.delete_installation.long WQ
\"
QW man_escape("\n"^[for a=apis_inst -> apicall(manapi a)]) WQ
\"
\"
.SH FILES
\"
.SS Config Files
\"
QW manfile(files.config) WQ
\"
.SS CITM Email Storage
\"
QW manfile(files.citm) WQ
\"
.SS Per-User API Tokens
\"
QW manfile(files.accounts) WQ
\" see `man 7 man-pages` for official header list of style guide
\" see "Macro Package", should be using the groff an.tmac package
\"
\" HEADERS
\"
\" NOTES
\" BUGS
\"
\" COPYRIGHT
